// Deprecated
//export interface WarbandConfig {
//    name: string;
//    color: string;
//    season: string;
//    iconLink: string;
//}

//export const WARBAAND_CONFIG: WarbandConfig[] = [
//    { name: "Blackpowder's Buccaneers", color: '#FF6384', season: '2024', iconLink: 'path/to/blackpowders-buccaneers-icon.png' },
//    { name: "Brethren of the Bolt", color: '#36A2EB', season: '2024', iconLink: 'path/to/brethren-of-the-bolt-icon.png' },
//    { name: "Chosen Axes", color: '#FFCE56', season: '2023', iconLink: 'path/to/chosen-axes-icon.png' },
//    { name: "Crimson Court", color: '#4BC0C0', season: '2023', iconLink: 'path/to/crimson-court-icon.png' },
//    { name: "Cyreni's Razors", color: '#9966FF', season: '2023', iconLink: 'path/to/cyrenis-razors-icon.png' },
//    { name: "Da Kunnin' Krew", color: '#FF9F40', season: '2024', iconLink: 'path/to/da-kunnin-krew-icon.png' },
//    { name: "Daggok's Stab-Ladz", color: '#FF6384', season: '2022', iconLink: 'path/to/daggoks-stab-ladz-icon.png' },
//    { name: "Domitan's Stormcoven", color: '#36A2EB', season: '2022', iconLink: 'path/to/domitans-stormcoven-icon.png' },
//    { name: "Dread Pageant", color: '#FFCE56', season: '2021', iconLink: 'path/to/dread-pageant-icon.png' },
//    { name: "Drepur's Wraithcreepers", color: '#4BC0C0', season: '2021', iconLink: 'path/to/drepurs-wraithcreepers-icon.png' },
//    { name: "Elathain's Soulraid", color: '#9966FF', season: '2020', iconLink: 'path/to/elathains-soulraid-icon.png' },
//    { name: "Emberwatch", color: '#FF9F40', season: '2020', iconLink: 'path/to/emberwatch-icon.png' },
//    { name: "Ephilim's Pandaemonium", color: '#FF6384', season: '2022', iconLink: 'path/to/ephilims-pandaemonium-icon.png' },
//    { name: "Exiled Dead", color: '#36A2EB', season: '2021', iconLink: 'path/to/exiled-dead-icon.png' },
//    { name: "Eyes of the Nine", color: '#FFCE56', season: '2020', iconLink: 'path/to/eyes-of-the-nine-icon.png' },
//    { name: "Farstriders", color: '#4BC0C0', season: '2021', iconLink: 'path/to/farstriders-icon.png' },
//    { name: "Garrek's Reavers", color: '#9966FF', season: '2021', iconLink: 'path/to/garreks-reavers-icon.png' },
//    { name: "Gnarlspirit Pack", color: '#FF9F40', season: '2024', iconLink: 'path/to/gnarlspirit-pack-icon.png' },
//    { name: "Godsworn Hunt", color: '#FF6384', season: '2024', iconLink: 'path/to/godsworn-hunt-icon.png' },
//    { name: "Gorechosen of Dromm", color: '#36A2EB', season: '2023', iconLink: 'path/to/gorechosen-of-dromm-icon.png' },
//    { name: "Grandfather's Gardeners", color: '#FFCE56', season: '2022', iconLink: 'path/to/grandfathers-gardeners-icon.png' },
//    { name: "Grashrak's Despoilers", color: '#4BC0C0', season: '2023', iconLink: 'path/to/grashraks-despoilers-icon.png' },
//    { name: "Grinkrak's Looncourt", color: '#9966FF', season: '2023', iconLink: 'path/to/grinkraks-looncourt-icon.png' },
//    { name: "Grymwatch", color: '#FF9F40', season: '2022', iconLink: 'path/to/grywatch-icon.png' },
//    { name: "Gryselle's Arenai", color: '#FF6384', season: '2022', iconLink: 'path/to/gryselles-arenai-icon.png' },
//    { name: "Headsmen's Curse", color: '#36A2EB', season: '2024', iconLink: 'path/to/headsmen-curse-icon.png' },
//    { name: "Hedkrakka's Madmob", color: '#FFCE56', season: '2024', iconLink: 'path/to/hedkrakkas-madmob-icon.png' },
//    { name: "Hexbane's Hunters", color: '#4BC0C0', season: '2023', iconLink: 'path/to/hexbanes-hunters-icon.png' },
//    { name: "Hrothgorn's Mantrappers", color: '#9966FF', season: '2022', iconLink: 'path/to/hrothgorns-mantrappers-icon.png' },
//    { name: "Ironskull's Boyz", color: '#FF9F40', season: '2023', iconLink: 'path/to/ironskulls-boyz-icon.png' },
//    { name: "Ironsoul's Condemners", color: '#FF6384', season: '2021', iconLink: 'path/to/ironsouls-condemners-icon.png' },
//    { name: "Jaws of Itzl", color: '#36A2EB', season: '2021', iconLink: 'path/to/jaws-of-itzl-icon.png' },
//    { name: "Kainan's Reapers", color: '#FFCE56', season: '2023', iconLink: 'path/to/kainans-reapers-icon.png' },
//    { name: "Khagra's Ravagers", color: '#4BC0C0', season: '2022', iconLink: 'path/to/khagras-ravagers-icon.png' },
//    { name: "Lady Harrow's Mournflight", color: '#9966FF', season: '2024', iconLink: 'path/to/lady-harrows-mournflight-icon.png' },
//    { name: "Magore's Fiends", color: '#FF9F40', season: '2021', iconLink: 'path/to/magores-fiends-icon.png' },
//    { name: "Mollog's Mob", color: '#FF6384', season: '2023', iconLink: 'path/to/mollogs-mob-icon.png' },
//    { name: "Morgok's Krushas", color: '#36A2EB', season: '2022', iconLink: 'path/to/morgoks-krushas-icon.png' },
//    { name: "Morgwaeth's Blade-Coven", color: '#FFCE56', season: '2024', iconLink: 'path/to/morgwaeths-blade-coven-icon.png' },
//    { name: "Myari's Purifiers", color: '#4BC0C0', season: '2021', iconLink: 'path/to/myaris-purifiers-icon.png' },
//    { name: "Rippa's Snarlfangs", color: '#9966FF', season: '2023', iconLink: 'path/to/rippas-snarlfangs-icon.png' },
//    { name: "Sepulchral Guard", color: '#FF9F40', season: '2022', iconLink: 'path/to/sepulchral-guard-icon.png' },
//    { name: "Shadeborn", color: '#FF6384', season: '2023', iconLink: 'path/to/shadeborn-icon.png' },
//    { name: "Skabbik's Plaguepack", color: '#36A2EB', season: '2021', iconLink: 'path/to/skabbiks-plaguepack-icon.png' },
//    { name: "Skaeth's Wild Hunt", color: '#FFCE56', season: '2021', iconLink: 'path/to/skaeths-wild-hunt-icon.png' },
//    { name: "Skinnerkin", color: '#4BC0C0', season: '2024', iconLink: 'path/to/skinnerkin-icon.png' },
//    { name: "Skittershank's Clawpack", color: '#9966FF', season: '2022', iconLink: 'path/to/skittershanks-clawpack-icon.png' },
//    { name: "Sons of Velmorn", color: '#FF9F40', season: '2023', iconLink: 'path/to/sons-of-velmorn-icon.png' },
//    { name: "Spiteclaw's Swarm", color: '#FF6384', season: '2022', iconLink: 'path/to/spiteclaws-swarm-icon.png' },
//    { name: "Starblood Stalkers", color: '#36A2EB', season: '2024', iconLink: 'path/to/starblood-stalkers-icon.png' },
//    { name: "Steelheart's Champions", color: '#FFCE56', season: '2021', iconLink: 'path/to/steelhearts-champions-icon.png' },
//    { name: "Storm of Celestus", color: '#4BC0C0', season: '2024', iconLink: 'path/to/storm-of-celestus-icon.png' },
//    { name: "Stormsire's Cursebreakers", color: '#9966FF', season: '2023', iconLink: 'path/to/stormsires-cursebreakers-icon.png' },
//    { name: "Thorns of the Briar Queen", color: '#FF9F40', season: '2021', iconLink: 'path/to/thorns-of-the-briar-queen-icon.png' },
//    { name: "Thricefold Discord", color: '#FF6384', season: '2023', iconLink: 'path/to/thricefold-discord-icon.png' },
//    { name: "Thundrik's Profiteers", color: '#36A2EB', season: '2022', iconLink: 'path/to/thundriks-profiteers-icon.png' },
//    { name: "Wurmspat", color: '#FFCE56', season: '2023', iconLink: 'path/to/wurmspat-icon.png' },
//    { name: "Xandire's Truthseekers", color: '#4BC0C0', season: '2022', iconLink: 'path/to/xandires-truthseekers-icon.png' },
//    { name: "Ylthari's Guardians", color: '#9966FF', season: '2024', iconLink: 'path/to/yltharis-guardians-icon.png' },
//    { name: "Zarbag's Gitz", color: '#FF9F40', season: '2021', iconLink: 'path/to/zarbags-gitz-icon.png' },
//    { name: "Zikkit's Tunnelpack", color: '#FF6384', season: '2024', iconLink: 'path/to/zikkits-tunnelpack-icon.png' },
//    { name: "Zondara's Gravebreakers", color: '#36A2EB', season: '2023', iconLink: 'path/to/zondaras-gravebreakers-icon.png' }
//];